### ISSUE TITLE
Support pull_request events

### ISSUE THREAD

**Issue by dardanos** [mr-smithers-excellent/docker-build-push#13]
The plugin works well for branch builds and tags but it doesn't support pull requests so it's hard to know if changes once applied to a branch will work.

You can see the limitation here:
https://github.com/mr-smithers-excellent/docker-build-push/blob/master/src/docker.js#L42:L46

During a PR there is a `GITHUB_REF` which has the value `refs/pull/:prNumber/merge`.
That can be used to create a tag: `pr-:prNumber-:sha`.

Thoughts?

**Comment by mr-smithers-excellent** [comment]
For this use case, I would typically use the Docker image from the source branch to test any changes. For instance, if I'm working on branch called `new-feature` and have submitted a pull request, I would test the most recent Docker image labeled `owner/image-name:new-feature-[latest-git-sha]`. The reason I'm not including builds on PRs is because this would be redundant. The PR would also point to the latest Git SHA. In this case that would be `owner/image-name:pr-123-[latest-git-sha]` where the Git SHA would match the one above.

**Comment by dardanos** [comment]
That's a fair point. Thanks, for the explanation
