### ISSUE TITLE
Why is there no switch to set whether to push all tags?

### ISSUE THREAD

**Issue by guomaoqiu** [mr-smithers-excellent/docker-build-push#232]
Hello, when I used this plug-in, I found that every time I push, the image on the github runner will be pushed again. When my container is not cleaned, a lot of images will accumulate on it, which will cause my working time. Variable length. I read your source code and used the  `--all-tags`  flag when pushing. Can you make it an optional option, the latest tag or all tags?

![image](https://github.com/mr-smithers-excellent/docker-build-push/assets/9714859/7af89ed6-2dd8-4242-9a13-c79d632240f7)

**Comment by guomaoqiu** [comment]
My requirement is to only push the most recently built image tag.

**Comment by mr-smithers-excellent** [comment]
Hi @guomaoqiu. Can you supply your workflow configuration please? Also, are you using a local or hosted runner?

**Comment by guomaoqiu** [comment]
> Hi @guomaoqiu. Can you supply your workflow configuration please? Also, are you using a local or hosted runner?

Thank you for your reply;
1. The workflow is as follows: https://github.com/nervosnetwork/ckb-explorer/blob/develop/.github/workflows/build.yml.
2. Using github hosting runner.

You can also see from the history records that when a lot of images are accumulated on the runner, all images will be pushed every time, which delays the developer's work progress. Please help solve the problem. The following example is: https://github.com/nervosnetwork/ckb-explorer/actions/runs/8596993633/job/23554704007

**Comment by mr-smithers-excellent** [comment]
I think this might have something to do with the Docker caching that you're using here. [This action](https://github.com/satackey/action-docker-layer-caching) does not seem to be actively supported, I wouldn't recommend using it. The last release was in 2020.

If you really need to use caching, I would go with [Docker's solution](https://docs.docker.com/build/ci/github-actions/cache/). Otherwise, I'd advise you to remove it and try the action again.
