### ISSUE TITLE
Input multiPlatform is set to true, skipping Docker push step

### ISSUE THREAD

**Issue by f18m** [mr-smithers-excellent/docker-build-push#236]
Hi,
I'm trying to use this action on this open-source project: https://github.com/eschava/psmqtt

My intent is to push a multi-platform docker image to ghcr.
At the end of the github pipeline I see:

```
#68 pushing layers 8.1s done
#68 pushing manifest for ghcr.io/eschava/psmqtt:master-d93a7dd@sha256:1c0a7b18d85c0708abdc41b225ce9757936701f6300bf0eb67e687084a942aa2
#68 pushing manifest for ghcr.io/eschava/psmqtt:master-d93a7dd@sha256:1c0a7b18d85c0708abdc41b225ce9757936701f6300bf0eb67e687084a942aa2 3.2s done
#68 DONE 12.4s
Input multiPlatform is set to true, skipping Docker push step...
```

does it mean that the push has been done (as the 'pushing layers' and 'pushing manifest' messages seem to indicate) or it was skipped (as the 'skipping Docker push step' message seems to indicate) ?
thanks!

**Comment by mr-smithers-excellent** [comment]
@f18m - the multiplatform `docker buildx build` command works a little bit differently than the traditional `docker build` command as it does take care of the push for you. I can confirm your images pushed, you're able to see them in GHCR [here](https://github.com/eschava/psmqtt/pkgs/container/psmqtt).

Maybe I can update that message, I do see how it would be misleading. It's essentially skipping the "traditional" docker push step since `buildx` already took care of it.

**Comment by f18m** [comment]
hi @mr-smithers-excellent ,
thanks for the answer; I think that updating the message would be a good idea, thanks!
