### ISSUE TITLE
branch tags

### ISSUE THREAD

**Issue by paretje** [mr-smithers-excellent/docker-build-push#34]
The algorithm to determine the docker tag for a git branch currently is:
```js
    // If we're not building a tag, use branch-prefix-{GIT_SHORT_SHA) as the Docker tag
    // refs/heads/jira-123/feature/something
    const branchName = ref.replace('refs/heads/', '');
    const branchPrefix = branchName.includes('/') ? branchName.substring(0, branchName.indexOf('/')) : branchName;
    dockerTag = `${branchPrefix}-${shortSha}`;
```

So given the example of git branches with a `feature` prefix, all branches will get very similar docker tags. Wouldn't it be more useful to use a more specific part of the branch name? Or to e.g. replace slashes with dashes?

**Comment by mr-smithers-excellent** [comment]
Hi @paretje - thanks for the feedback. This is admittedly a difficult problem to design an algorithm around due to the numerous branch-naming strategies people use. You could always choose to override with your own tag name with the `tags` input. Here's an example of the current algorithm. We are already replacing slashes with dashes. Could you give an example of what you are proposing here?

| Trigger                  | Commit SHA | Docker Tag           |
|--------------------------|------------|----------------------|
| /refs/tags/v1.0          | N/A        | v1.0                 |
| /refs/heads/dev          | 1234567    | dev-1234567          |
| /refs/heads/master       | 1234567    | master-1234567       |
| /refs/heads/SOME-feature | 1234567    | some-feature-1234567 |

**Comment by paretje** [comment]
Well, no, currently, the first part is used of the actual branch name:

| Trigger                  | Commit SHA | Docker Tag           |
|--------------------------|------------|----------------------|
| /refs/tags/v1.0          | N/A        | v1.0                 |
| /refs/heads/dev          | 1234567    | dev-1234567          |
| /refs/heads/master       | 1234567    | master-1234567       |
| /refs/heads/feature/SOME | 1234567    | feature-1234567      |

I would propose either:
| Trigger                  | Commit SHA | Docker Tag           |
|--------------------------|------------|----------------------|
| /refs/tags/v1.0          | N/A        | v1.0                 |
| /refs/heads/dev          | 1234567    | dev-1234567          |
| /refs/heads/master       | 1234567    | master-1234567       |
| /refs/heads/feature/SOME | 1234567    | feature-some-1234567 |

Or alternatively:
| Trigger                  | Commit SHA | Docker Tag           |
|--------------------------|------------|----------------------|
| /refs/tags/v1.0          | N/A        | v1.0                 |
| /refs/heads/dev          | 1234567    | dev-1234567          |
| /refs/heads/master       | 1234567    | master-1234567       |
| /refs/heads/feature/SOME | 1234567    | some-1234567         |

**Comment by mr-smithers-excellent** [comment]
We could certainly change around the logic to include the full Git branch name, replacing slashes with dashes. We would just need to adhere to the [128-character limit for Docker tags](https://docs.docker.com/engine/reference/commandline/tag/#extended-description).  Is this something you'd like to submit a PR for?  Would be greatly appreciated.

**Comment by paretje** [comment]
I will implement this and submit a PR.
